# set via vscode settings.json -> "rest-client.environmentVariables"
# also ctrl shift P -> rest client: switch environment -> local
@openweathermapapikey = {{teaweatheropenweatherapikey}}
@arcgisapikey = {{teaweatherarcgisapikey}}

### 
GET https://api.openweathermap.org/data/2.5/forecast?lat=51.5072&lon=-0.11&appid={{openweathermapapikey}}

############# ARCGIS ##############
### geocoding with all fields
GET https://geocode-api.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates?address=trafalgra+square&outFields=*&f=json&token={{arcgisapikey}}
### with only specific fields
GET https://geocode-api.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates?address=trafalgra+square&outFields=Type,Place_addr,PlaceName,Country,CntryName&f=json&token={{arcgisapikey}}