HTTP/1.1 200 
Date: Wed, 01 Mar 2023 13:27:35 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 2480
Connection: close
Cache-Control: max-age=0,must-revalidate
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Vary: Origin
Server: 
Set-Cookie: AGS_ROLES="K2+{redacted}/{redacted}"; Version=1; Max-Age=60; Expires=Wed, 01-Mar-2023 13:28:35 GMT; Path=/arcgis/rest; Secure; HttpOnly
ETag: "3af5ee9e"
Content-Encoding: gzip
X-Region: eu-central-1

{
  "spatialReference": {
    "wkid": 4326,
    "latestWkid": 4326
  },
  "candidates": [
    {
      "address": "Trafalgar Square",
      "location": {
        "x": -0.12734999999997854,
        "y": 51.507710000000031
      },
      "score": 100,
      "attributes": {
        "Loc_name": "World",
        "Status": "T",
        "Score": 100,
        "Match_addr": "Trafalgar Square",
        "LongLabel": "Trafalgar Square, London, England, WC2N 5, GBR",
        "ShortLabel": "Trafalgar Square",
        "Addr_type": "POI",
        "Type": "Tourist Attraction",
        "PlaceName": "Trafalgar Square",
        "Place_addr": "Trafalgar Square, London, England, WC2N 5",
        "Phone": "",
        "URL": "",
        "Rank": 17,
        "AddBldg": "",
        "AddNum": "",
        "AddNumFrom": "",
        "AddNumTo": "",
        "AddRange": "",
        "Side": "",
        "StPreDir": "",
        "StPreType": "",
        "StName": "Trafalgar",
        "StType": "Square",
        "StDir": "",
        "BldgType": "",
        "BldgName": "",
        "LevelType": "",
        "LevelName": "",
        "UnitType": "",
        "UnitName": "",
        "SubAddr": "",
        "StAddr": "Trafalgar Square",
        "Block": "",
        "Sector": "",
        "Nbrhd": "",
        "District": "",
        "City": "London",
        "MetroArea": "",
        "Subregion": "London",
        "Region": "England",
        "RegionAbbr": "ENG",
        "Territory": "",
        "Zone": "Charing Cross",
        "Postal": "WC2N 5",
        "PostalExt": "",
        "Country": "GBR",
        "CntryName": "United Kingdom",
        "LangCode": "ENG",
        "Distance": 0,
        "X": -0.12734999999997854,
        "Y": 51.507710000000031,
        "DisplayX": -0.12734999999997854,
        "DisplayY": 51.507710000000031,
        "Xmin": -0.13234999999997854,
        "Xmax": -0.12234999999997853,
        "Ymin": 51.502710000000029,
        "Ymax": 51.512710000000034,
        "ExInfo": ""
      },
      "extent": {
        "xmin": -0.13234999999997854,
        "ymin": 51.502710000000029,
        "xmax": -0.12234999999997853,
        "ymax": 51.512710000000034
      }
    },
    {
      "address": "Trafalgar Square",
      "location": {
        "x": -80.143675999999971,
        "y": 26.649286000000075
      },
      "score": 100,
      "attributes": {
        "Loc_name": "World",
        "Status": "T",
        "Score": 100,
        "Match_addr": "Trafalgar Square",
        "LongLabel": "Trafalgar Square, 6342 Forest Hill Blvd, West Palm Beach, FL, 33415, USA",
        "ShortLabel": "Trafalgar Square",
        "Addr_type": "POI",
        "Type": "Shopping Center",
        "PlaceName": "Trafalgar Square",
        "Place_addr": "6342 Forest Hill Blvd, West Palm Beach, Florida, 33415",
        "Phone": "",
        "URL": "",
        "Rank": 19,
        "AddBldg": "",
        "AddNum": "6342",
        "AddNumFrom": "",
        "AddNumTo": "",
        "AddRange": "",
        "Side": "",
        "StPreDir": "",
        "StPreType": "",
        "StName": "Forest Hill",
        "StType": "Blvd",
        "StDir": "",
        "BldgType": "",
        "BldgName": "",
        "LevelType": "",
        "LevelName": "",
        "UnitType": "",
        "UnitName": "",
        "SubAddr": "",
        "StAddr": "6342 Forest Hill Blvd",
        "Block": "",
        "Sector": "",
        "Nbrhd": "",
        "District": "",
        "City": "West Palm Beach",
        "MetroArea": "",
        "Subregion": "Palm Beach County",
        "Region": "Florida",
        "RegionAbbr": "FL",
        "Territory": "",
        "Zone": "",
        "Postal": "33415",
        "PostalExt": "",
        "Country": "USA",
        "CntryName": "United States",
        "LangCode": "ENG",
        "Distance": 0,
        "X": -80.143675999999971,
        "Y": 26.649286000000075,
        "DisplayX": -80.143675999999971,
        "DisplayY": 26.649286000000075,
        "Xmin": -80.144675999999976,
        "Xmax": -80.142675999999966,
        "Ymin": 26.648286000000073,
        "Ymax": 26.650286000000076,
        "ExInfo": ""
      },
      "extent": {
        "xmin": -80.144675999999976,
        "ymin": 26.648286000000073,
        "xmax": -80.142675999999966,
        "ymax": 26.650286000000076
      }
    },
    {
      "address": "Trafalgar Square",
      "location": {
        "x": -123.44418799999994,
        "y": 48.575345000000027
      },
      "score": 100,
      "attributes": {
        "Loc_name": "World",
        "Status": "T",
        "Score": 100,
        "Match_addr": "Trafalgar Square",
        "LongLabel": "Trafalgar Square, 7103 W Saanich Rd, Brentwood Bay, BC, V8M 1R1, CAN",
        "ShortLabel": "Trafalgar Square",
        "Addr_type": "POI",
        "Type": "Shopping Center",
        "PlaceName": "Trafalgar Square",
        "Place_addr": "7103 W Saanich Rd, Brentwood Bay, British Columbia, V8M 1R1",
        "Phone": "",
        "URL": "",
        "Rank": 19,
        "AddBldg": "",
        "AddNum": "7103",
        "AddNumFrom": "",
        "AddNumTo": "",
        "AddRange": "",
        "Side": "",
        "StPreDir": "W",
        "StPreType": "",
        "StName": "Saanich",
        "StType": "Rd",
        "StDir": "",
        "BldgType": "",
        "BldgName": "",
        "LevelType": "",
        "LevelName": "",
        "UnitType": "",
        "UnitName": "",
        "SubAddr": "",
        "StAddr": "7103 W Saanich Rd",
        "Block": "",
        "Sector": "",
        "Nbrhd": "",
        "District": "",
        "City": "Brentwood Bay",
        "MetroArea": "",
        "Subregion": "Capital",
        "Region": "British Columbia",
        "RegionAbbr": "BC",
        "Territory": "",
        "Zone": "",
        "Postal": "V8M",
        "PostalExt": "1R1",
        "Country": "CAN",
        "CntryName": "Canada",
        "LangCode": "ENG",
        "Distance": 0,
        "X": -123.44418799999994,
        "Y": 48.575345000000027,
        "DisplayX": -123.44418799999994,
        "DisplayY": 48.575345000000027,
        "Xmin": -123.44518799999994,
        "Xmax": -123.44318799999994,
        "Ymin": 48.574345000000029,
        "Ymax": 48.576345000000025,
        "ExInfo": ""
      },
      "extent": {
        "xmin": -123.44518799999994,
        "ymin": 48.574345000000029,
        "xmax": -123.44318799999994,
        "ymax": 48.576345000000025
      }
    },
    {
      "address": "Trafalgar Square",
      "location": {
        "x": 9.6622100000000728,
        "y": 4.0897000000000503
      },
      "score": 100,
      "attributes": {
        "Loc_name": "World",
        "Status": "T",
        "Score": 100,
        "Match_addr": "Trafalgar Square",
        "LongLabel": "Trafalgar Square, Banberi, Wouri, Littoral, CMR",
        "ShortLabel": "Trafalgar Square",
        "Addr_type": "POI",
        "Type": "Specialty Store",
        "PlaceName": "Trafalgar Square",
        "Place_addr": "Banberi, Wouri, Littoral",
        "Phone": "",
        "URL": "",
        "Rank": 19,
        "AddBldg": "",
        "AddNum": "",
        "AddNumFrom": "",
        "AddNumTo": "",
        "AddRange": "",
        "Side": "",
        "StPreDir": "",
        "StPreType": "",
        "StName": "",
        "StType": "",
        "StDir": "",
        "BldgType": "",
        "BldgName": "",
        "LevelType": "",
        "LevelName": "",
        "UnitType": "",
        "UnitName": "",
        "SubAddr": "",
        "StAddr": "",
        "Block": "",
        "Sector": "",
        "Nbrhd": "Banberi",
        "District": "",
        "City": "Wouri",
        "MetroArea": "",
        "Subregion": "",
        "Region": "Littoral",
        "RegionAbbr": "",
        "Territory": "",
        "Zone": "",
        "Postal": "",
        "PostalExt": "",
        "Country": "CMR",
        "CntryName": "Cameroun",
        "LangCode": "FRE",
        "Distance": 0,
        "X": 9.6622100000000728,
        "Y": 4.0897000000000503,
        "DisplayX": 9.6622100000000728,
        "DisplayY": 4.0897000000000503,
        "Xmin": 9.657210000000072,
        "Xmax": 9.6672100000000736,
        "Ymin": 4.0847000000000504,
        "Ymax": 4.0947000000000502,
        "ExInfo": ""
      },
      "extent": {
        "xmin": 9.657210000000072,
        "ymin": 4.0847000000000504,
        "xmax": 9.6672100000000736,
        "ymax": 4.0947000000000502
      }
    },
    {
      "address": "Trafalgar Square",
      "location": {
        "x": 175.05396000000007,
        "y": -39.936269999999979
      },
      "score": 100,
      "attributes": {
        "Loc_name": "World",
        "Status": "T",
        "Score": 100,
        "Match_addr": "Trafalgar Square",
        "LongLabel": "Trafalgar Square, 100 Taupo Quay, Whanganui, 4500, NZL",
        "ShortLabel": "Trafalgar Square",
        "Addr_type": "POI",
        "Type": "Shopping Center",
        "PlaceName": "Trafalgar Square",
        "Place_addr": "100 Taupo Quay, Whanganui, 4500",
        "Phone": "+64 6-3480314",
        "URL": "https://trafalgarsquare.co.nz/",
        "Rank": 19,
        "AddBldg": "",
        "AddNum": "100",
        "AddNumFrom": "",
        "AddNumTo": "",
        "AddRange": "",
        "Side": "L",
        "StPreDir": "",
        "StPreType": "",
        "StName": "Taupo",
        "StType": "Quay",
        "StDir": "",
        "BldgType": "",
        "BldgName": "",
        "LevelType": "",
        "LevelName": "",
        "UnitType": "",
        "UnitName": "",
        "SubAddr": "",
        "StAddr": "100 Taupo Quay",
        "Block": "",
        "Sector": "",
        "Nbrhd": "",
        "District": "Whanganui",
        "City": "Whanganui",
        "MetroArea": "",
        "Subregion": "",
        "Region": "",
        "RegionAbbr": "",
        "Territory": "",
        "Zone": "",
        "Postal": "4500",
        "PostalExt": "",
        "Country": "NZL",
        "CntryName": "New Zealand",
        "LangCode": "ENG",
        "Distance": 0,
        "X": 175.05396000000007,
        "Y": -39.936269999999979,
        "DisplayX": 175.05396000000007,
        "DisplayY": -39.936269999999979,
        "Xmin": 175.04896000000008,
        "Xmax": 175.05896000000007,
        "Ymin": -39.941269999999982,
        "Ymax": -39.931269999999977,
        "ExInfo": ""
      },
      "extent": {
        "xmin": 175.04896000000008,
        "ymin": -39.941269999999982,
        "xmax": 175.05896000000007,
        "ymax": -39.931269999999977
      }
    },
    {
      "address": "Trafalgar Square",
      "location": {
        "x": 26.767200000000059,
        "y": -27.974039999999945
      },
      "score": 100,
      "attributes": {
        "Loc_name": "World",
        "Status": "T",
        "Score": 100,
        "Match_addr": "Trafalgar Square",
        "LongLabel": "Trafalgar Square, 21 Theron St, Rietzpark, Lejweleputswa, Free State, 9459, ZAF",
        "ShortLabel": "Trafalgar Square",
        "Addr_type": "POI",
        "Type": "Bar or Pub",
        "PlaceName": "Trafalgar Square",
        "Place_addr": "21 Theron St, Matjhabeng, Free State, 9459",
        "Phone": "",
        "URL": "",
        "Rank": 19,
        "AddBldg": "",
        "AddNum": "21",
        "AddNumFrom": "",
        "AddNumTo": "",
        "AddRange": "",
        "Side": "R",
        "StPreDir": "",
        "StPreType": "",
        "StName": "Theron",
        "StType": "St",
        "StDir": "",
        "BldgType": "",
        "BldgName": "",
        "LevelType": "",
        "LevelName": "",
        "UnitType": "",
        "UnitName": "",
        "SubAddr": "",
        "StAddr": "21 Theron St",
        "Block": "",
        "Sector": "",
        "Nbrhd": "",
        "District": "Rietzpark",
        "City": "Matjhabeng",
        "MetroArea": "",
        "Subregion": "Lejweleputswa",
        "Region": "Free State",
        "RegionAbbr": "",
        "Territory": "",
        "Zone": "",
        "Postal": "9459",
        "PostalExt": "",
        "Country": "ZAF",
        "CntryName": "South Africa",
        "LangCode": "ENG",
        "Distance": 0,
        "X": 26.767200000000059,
        "Y": -27.974039999999945,
        "DisplayX": 26.767200000000059,
        "DisplayY": -27.974039999999945,
        "Xmin": 26.76220000000006,
        "Xmax": 26.772200000000058,
        "Ymin": -27.979039999999944,
        "Ymax": -27.969039999999946,
        "ExInfo": ""
      },
      "extent": {
        "xmin": 26.76220000000006,
        "ymin": -27.979039999999944,
        "xmax": 26.772200000000058,
        "ymax": -27.969039999999946
      }
    },
    {
      "address": "Trafalgar Square, Carrollwood, Florida",
      "location": {
        "x": -82.515399999999943,
        "y": 28.041600000000074
      },
      "score": 100,
      "attributes": {
        "Loc_name": "World",
        "Status": "M",
        "Score": 100,
        "Match_addr": "Trafalgar Square, Carrollwood, Florida",
        "LongLabel": "Trafalgar Square, Carrollwood, FL, USA",
        "ShortLabel": "Trafalgar Square",
        "Addr_type": "Locality",
        "Type": "City",
        "PlaceName": "Trafalgar Square",
        "Place_addr": "Carrollwood, Florida",
        "Phone": "",
        "URL": "",
        "Rank": 20,
        "AddBldg": "",
        "AddNum": "",
        "AddNumFrom": "",
        "AddNumTo": "",
        "AddRange": "",
        "Side": "",
        "StPreDir": "",
        "StPreType": "",
        "StName": "",
        "StType": "",
        "StDir": "",
        "BldgType": "",
        "BldgName": "",
        "LevelType": "",
        "LevelName": "",
        "UnitType": "",
        "UnitName": "",
        "SubAddr": "",
        "StAddr": "",
        "Block": "",
        "Sector": "",
        "Nbrhd": "",
        "District": "Trafalgar Square",
        "City": "Carrollwood",
        "MetroArea": "",
        "Subregion": "Hillsborough County",
        "Region": "Florida",
        "RegionAbbr": "FL",
        "Territory": "",
        "Zone": "",
        "Postal": "",
        "PostalExt": "",
        "Country": "USA",
        "CntryName": "United States",
        "LangCode": "ENG",
        "Distance": 0,
        "X": -82.515399999999943,
        "Y": 28.041600000000074,
        "DisplayX": -82.515399999999943,
        "DisplayY": 28.041600000000074,
        "Xmin": -82.765399999999943,
        "Xmax": -82.265399999999943,
        "Ymin": 27.791600000000074,
        "Ymax": 28.291600000000074,
        "ExInfo": ""
      },
      "extent": {
        "xmin": -82.765399999999943,
        "ymin": 27.791600000000074,
        "xmax": -82.265399999999943,
        "ymax": 28.291600000000074
      }
    },
    {
      "address": "Trafalgar Square",
      "location": {
        "x": -0.12976999999995087,
        "y": 51.507200000000068
      },
      "score": 100,
      "attributes": {
        "Loc_name": "World",
        "Status": "T",
        "Score": 100,
        "Match_addr": "Trafalgar Square",
        "LongLabel": "Trafalgar Square, Cockspur Court, London, England, SW1Y 5, GBR",
        "ShortLabel": "Trafalgar Square",
        "Addr_type": "POI",
        "Type": "Parking",
        "PlaceName": "Trafalgar Square",
        "Place_addr": "Cockspur Court, London, England, SW1Y 5",
        "Phone": "+44 20-79301565",
        "URL": "",
        "Rank": 22,
        "AddBldg": "",
        "AddNum": "",
        "AddNumFrom": "",
        "AddNumTo": "",
        "AddRange": "",
        "Side": "",
        "StPreDir": "",
        "StPreType": "",
        "StName": "Cockspur",
        "StType": "Court",
        "StDir": "",
        "BldgType": "",
        "BldgName": "",
        "LevelType": "",
        "LevelName": "",
        "UnitType": "",
        "UnitName": "",
        "SubAddr": "",
        "StAddr": "Cockspur Court",
        "Block": "",
        "Sector": "",
        "Nbrhd": "",
        "District": "",
        "City": "London",
        "MetroArea": "",
        "Subregion": "London",
        "Region": "England",
        "RegionAbbr": "ENG",
        "Territory": "",
        "Zone": "St James's",
        "Postal": "SW1Y 5",
        "PostalExt": "",
        "Country": "GBR",
        "CntryName": "United Kingdom",
        "LangCode": "ENG",
        "Distance": 0,
        "X": -0.12976999999995087,
        "Y": 51.507200000000068,
        "DisplayX": -0.12976999999995087,
        "DisplayY": 51.507200000000068,
        "Xmin": -0.13476999999995087,
        "Xmax": -0.12476999999995086,
        "Ymin": 51.502200000000066,
        "Ymax": 51.512200000000071,
        "ExInfo": ""
      },
      "extent": {
        "xmin": -0.13476999999995087,
        "ymin": 51.502200000000066,
        "xmax": -0.12476999999995086,
        "ymax": 51.512200000000071
      }
    },
    {
      "address": "Trafalgar Square",
      "location": {
        "x": -71.514789999999948,
        "y": 42.789250000000038
      },
      "score": 100,
      "attributes": {
        "Loc_name": "World",
        "Status": "T",
        "Score": 100,
        "Match_addr": "Trafalgar Square",
        "LongLabel": "Trafalgar Square, City of Nashua, NH, USA",
        "ShortLabel": "Trafalgar Square",
        "Addr_type": "POI",
        "Type": "Building",
        "PlaceName": "Trafalgar Square",
        "Place_addr": "City of Nashua, New Hampshire",
        "Phone": "",
        "URL": "",
        "Rank": 24,
        "AddBldg": "",
        "AddNum": "",
        "AddNumFrom": "",
        "AddNumTo": "",
        "AddRange": "",
        "Side": "",
        "StPreDir": "",
        "StPreType": "",
        "StName": "",
        "StType": "",
        "StDir": "",
        "BldgType": "",
        "BldgName": "",
        "LevelType": "",
        "LevelName": "",
        "UnitType": "",
        "UnitName": "",
        "SubAddr": "",
        "StAddr": "",
        "Block": "",
        "Sector": "",
        "Nbrhd": "",
        "District": "",
        "City": "City of Nashua",
        "MetroArea": "",
        "Subregion": "Hillsborough County",
        "Region": "New Hampshire",
        "RegionAbbr": "NH",
        "Territory": "",
        "Zone": "",
        "Postal": "",
        "PostalExt": "",
        "Country": "USA",
        "CntryName": "United States",
        "LangCode": "ENG",
        "Distance": 0,
        "X": -71.514789999999948,
        "Y": 42.789250000000038,
        "DisplayX": -71.514789999999948,
        "DisplayY": 42.789250000000038,
        "Xmin": -71.519789999999944,
        "Xmax": -71.509789999999953,
        "Ymin": 42.784250000000036,
        "Ymax": 42.794250000000041,
        "ExInfo": ""
      },
      "extent": {
        "xmin": -71.519789999999944,
        "ymin": 42.784250000000036,
        "xmax": -71.509789999999953,
        "ymax": 42.794250000000041
      }
    },
    {
      "address": "Trafalgar Square",
      "location": {
        "x": 151.30119000000002,
        "y": -33.648499999999956
      },
      "score": 100,
      "attributes": {
        "Loc_name": "World",
        "Status": "T",
        "Score": 100,
        "Match_addr": "Trafalgar Square",
        "LongLabel": "Trafalgar Square, New South Wales, AUS",
        "ShortLabel": "Trafalgar Square",
        "Addr_type": "POI",
        "Type": "Nature Reserve",
        "PlaceName": "Trafalgar Square",
        "Place_addr": "New South Wales",
        "Phone": "",
        "URL": "",
        "Rank": 24,
        "AddBldg": "",
        "AddNum": "",
        "AddNumFrom": "",
        "AddNumTo": "",
        "AddRange": "",
        "Side": "",
        "StPreDir": "",
        "StPreType": "",
        "StName": "",
        "StType": "",
        "StDir": "",
        "BldgType": "",
        "BldgName": "",
        "LevelType": "",
        "LevelName": "",
        "UnitType": "",
        "UnitName": "",
        "SubAddr": "",
        "StAddr": "",
        "Block": "",
        "Sector": "",
        "Nbrhd": "",
        "District": "",
        "City": "",
        "MetroArea": "",
        "Subregion": "",
        "Region": "New South Wales",
        "RegionAbbr": "NSW",
        "Territory": "",
        "Zone": "",
        "Postal": "",
        "PostalExt": "",
        "Country": "AUS",
        "CntryName": "Australia",
        "LangCode": "ENG",
        "Distance": 0,
        "X": 151.30119000000002,
        "Y": -33.648499999999956,
        "DisplayX": 151.30119000000002,
        "DisplayY": -33.648499999999956,
        "Xmin": 150.55119000000002,
        "Xmax": 152.05119000000002,
        "Ymin": -34.398499999999956,
        "Ymax": -32.898499999999956,
        "ExInfo": ""
      },
      "extent": {
        "xmin": 150.55119000000002,
        "ymin": -34.398499999999956,
        "xmax": 152.05119000000002,
        "ymax": -32.898499999999956
      }
    },
    {
      "address": "Trafalgar Square",
      "location": {
        "x": 27.913010000000043,
        "y": -26.166289999999947
      },
      "score": 100,
      "attributes": {
        "Loc_name": "World",
        "Status": "T",
        "Score": 100,
        "Match_addr": "Trafalgar Square",
        "LongLabel": "Trafalgar Square, Barry Hertzog Dr, Florida Park, Johannesburg, Gauteng, 1709, ZAF",
        "ShortLabel": "Trafalgar Square",
        "Addr_type": "POI",
        "Type": "Residential Area",
        "PlaceName": "Trafalgar Square",
        "Place_addr": "Barry Hertzog Dr, Johannesburg, Gauteng, 1709",
        "Phone": "",
        "URL": "",
        "Rank": 25,
        "AddBldg": "",
        "AddNum": "",
        "AddNumFrom": "",
        "AddNumTo": "",
        "AddRange": "",
        "Side": "",
        "StPreDir": "",
        "StPreType": "",
        "StName": "Barry Hertzog",
        "StType": "Dr",
        "StDir": "",
        "BldgType": "",
        "BldgName": "",
        "LevelType": "",
        "LevelName": "",
        "UnitType": "",
        "UnitName": "",
        "SubAddr": "",
        "StAddr": "Barry Hertzog Dr",
        "Block": "",
        "Sector": "",
        "Nbrhd": "",
        "District": "Florida Park",
        "City": "Johannesburg",
        "MetroArea": "",
        "Subregion": "Johannesburg",
        "Region": "Gauteng",
        "RegionAbbr": "",
        "Territory": "",
        "Zone": "Roodepoort",
        "Postal": "1709",
        "PostalExt": "",
        "Country": "ZAF",
        "CntryName": "South Africa",
        "LangCode": "ENG",
        "Distance": 0,
        "X": 27.913010000000043,
        "Y": -26.166289999999947,
        "DisplayX": 27.913010000000043,
        "DisplayY": -26.166289999999947,
        "Xmin": 27.908010000000044,
        "Xmax": 27.918010000000042,
        "Ymin": -26.171289999999946,
        "Ymax": -26.161289999999948,
        "ExInfo": ""
      },
      "extent": {
        "xmin": 27.908010000000044,
        "ymin": -26.171289999999946,
        "xmax": 27.918010000000042,
        "ymax": -26.161289999999948
      }
    }
  ]
}
